# Generated by Django 4.2.2 on 2023-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
