# Generated by Django 4.2.2 on 2023-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('CustomerPassword', models.CharField(max_length=200)),
                ('CustomerPhoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
