# Generated by Django 4.2.2 on 2023-07-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_customer_phone_number_order_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product_id',
            new_name='Product',
        ),
    ]
