# Generated by Django 4.2.2 on 2023-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_status',
            field=models.BooleanField(default=False),
        ),
    ]
